import './globals.css'
import type { Metadata } from 'next'
import { Inter, Prompt } from 'next/font/google'
import Header from './components/Header'

import Promptinput from './components/Promptinput'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Promptinput/>
        {children}
      </body>
    </html>
  )
}
